name = "CentroidalVoronoiController"
uuid = "f1887b2c-1188-4ed8-bdb2-c2d92e877ee6"
authors = ["Kyle Brown <kylejbrown17@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
